# Numpy Indexing_Selection

Indexing can be done in numpy by using an array as an index. In case of slice, a view or shallow copy of the array is returned but in index array a copy of the original array is returned. Numpy arrays can be indexed with other arrays or any other sequence with the exception of tuples. The last element is indexed by -1 second last by -2 and so on.

In [1]:
import numpy as np

In [3]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [5]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [7]:
arr[5:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
arr[:5]

array([1, 2, 3, 4, 5])

In [10]:
arr[:5] = 50
arr

array([50, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [12]:
arr[2] = 20
arr

array([50, 50, 20, 50, 50,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[1:2]

array([[4, 5, 6]])

In [17]:
arr[2:3]

array([[7, 8, 9]])

In [18]:
arr[:-1]

array([[1, 2, 3],
       [4, 5, 6]])