# Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [85]:
import numpy as np

In [86]:
l = [1,2,3,4]
type(l)

list

To Convert the list into an array we use np.array

In [87]:
mylist = np.array(l)
mylist

array([1, 2, 3, 4])

In [88]:
type(mylist)

numpy.ndarray

Multidimensional Arrays

In [89]:
l = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
mylist = np.array(l)
mylist

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
l = [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]
mylist = np.array(l)
mylist

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [92]:
np.ones(5)

array([1., 1., 1., 1., 1.])

* Return evenly spaced numbers over a specified interval.
* np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0)

In [93]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

np.eye() Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [94]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Also we can create numpy array by using np.arange()
* np.arange() takes the following :--
* Start Index
* End Index [n-1]
* Step Size

In [95]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [96]:
arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [97]:
print(arr.min())
print(arr.max())
print(arr.mean())

0
18
9.0


In [98]:
np.arange(-2,-10,-2)

array([-2, -4, -6, -8])

Random Class implementing all of the random number distributions

In [99]:
np.random.rand(10)

array([0.39252924, 0.09346037, 0.82110566, 0.15115202, 0.38411445,
       0.94426071, 0.98762547, 0.45630455, 0.82612284, 0.25137413])

Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [`low`, `high`). If`high` is None (the default), then results are from [0, `low`).

In [100]:
np.random.randint(10)

9

In [101]:
np.random.randint(0,10,3)

array([1, 2, 8])

In [102]:
np.random.randint(0,20,(2,3))

array([[ 9,  5,  0],
       [18,  3, 16]])

This is a convenience function for users porting code from Matlab,and wraps `random_sample`. That function takes a tuple to specify the size of the output, which is consistent with other NumPy functions like `numpy.zeros` and `numpy.ones`.

In [103]:
np.random.rand(1,10)

array([[0.2350386 , 0.65996495, 0.21495319, 0.20304662, 0.38286511,
        0.2248728 , 0.1146488 , 0.58301705, 0.23264106, 0.55651819]])

In [104]:
np.random.rand(1,6,5)

array([[[5.23810885e-01, 3.50958224e-01, 7.05331613e-01, 8.20703741e-01,
         1.34563003e-01],
        [6.04726160e-01, 2.83148276e-01, 5.06407820e-01, 3.84604283e-02,
         3.32444096e-01],
        [2.72531491e-04, 6.64655466e-01, 3.77440665e-01, 7.47581968e-01,
         1.40575782e-01],
        [3.88049453e-01, 8.66491641e-01, 9.56853326e-01, 4.86553669e-01,
         1.05933059e-01],
        [3.40037289e-01, 8.35570794e-01, 4.65441626e-01, 9.28561081e-02,
         8.54694143e-01],
        [3.37258186e-01, 6.06146751e-01, 1.12664601e-01, 5.43920447e-01,
         7.20798582e-01]]])

This is a convenience, legacy function. The best practice is to **not** reseed a BitGenerator, rather to recreate a new one. This method is here for legacy reasons. The Values will be constant not be a random numbers

In [105]:
np.random.seed(10)
np.random.rand(1,10)

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
        0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [106]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Returns an array containing the same data with a new shape.


In [107]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
arr.reshape(3,6) ## Here we will get an error because the array can not be set in 3*6 = 18 matrix of size 10

ValueError: cannot reshape array of size 10 into shape (3,6)

In [109]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [110]:
arr = np.arange(1,19)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.

In [111]:
arr.shape

(18,)

In [112]:
new = arr.reshape(9,2)
new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [113]:
new.shape

(9, 2)